[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
evm_version = "shanghai"
fuzz = { runs = 100, seed = "0xd13f0bfb" }
fuzz_max_global_rejects = 100_000_000
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.25"
src = "src"
test = "test"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "swap-helpers/=lib/swap-helpers/",
    "mock-tokens/=lib/mock-tokens",
]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
